package banquemisr.challenge05.TaskManagementSystem.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Represents a notification sent to a user.
 * This entity includes the message content, its read status,
 * the timestamp when it was created, and the user to whom it is associated.
 * <p>
 * Notifications are typically used to inform users of certain actions or events
 * related to tasks or other system activities.
 * </p>
 */
@Builder
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Notification {

    /**
     * The unique identifier for this notification.
     * It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The message content of the notification.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String message;

    /**
     * Indicates whether the notification has been sent to the user.
     * This field defaults to true (sent).
     */
    @Column(nullable = false)
    private Boolean isSent;

    /**
     * The timestamp when the notification was created.
     * This field is automatically set to the current date and time upon creation.
     */
    @Column(nullable = false)
    private LocalDateTime timestamp = LocalDateTime.now();

    /**
     * The user to whom this notification is associated.
     * A notification is sent to one user at a time.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
}
