package banquemisr.challenge05.TaskManagementSystem.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.Set;

/**
 * Represents a task in the task management system.
 * A task contains various attributes such as title, description, status, priority,
 * due date, users associated with the task, and the user who created it.
 * <p>
 * This entity extends the {@link BaseEntity} class, which provides the creation and
 * modification timestamps, and it is associated with multiple users through a many-to-many relationship.
 * </p>
 */
@Entity
@Table(name = "tasks")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Task extends BaseEntity {

    /**
     * The unique identifier for the task.
     * It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the task.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String title;

    /**
     * A description of the task, providing additional details.
     * This field is optional, and its length is limited to 300 characters.
     */
    @Column(length = 300)
    private String description;

    /**
     * The current status of the task (e.g., "To Do", "In Progress", "Completed").
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String status;

    /**
     * The priority of the task (e.g., "High", "Medium", "Low").
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String priority;

    /**
     * The due date of the task.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private LocalDate dueDate;

    /**
     * A many-to-many relationship between tasks and users.
     * A task can be assigned to multiple users, and each user can be associated with multiple tasks.
     */
    @ManyToMany
    @JoinTable(
            name = "task_users",
            joinColumns = @JoinColumn(name = "task_id"),
            inverseJoinColumns = @JoinColumn(name = "user_id")
    )
    private Set<User> users;

    /**
     * The username of the person who created the task.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String createdBy;
}
